```{r}
library(tidyverse)
library(tidymodels)
library(caret)
library(gridExtra)
library(ranger)
library(vip)
library(skimr)
library(ggplot2)
library(GGally)
library(ggcorrplot)
library(ROCR)
library(mice)
library(rpart) #for classification trees
library(rpart.plot) #for plotting trees
```



```{r}
#Read in Data
test = read_csv("/Users/gregwolcott/Documents/UNCW/BAN 502 - Predictive Analytics/Course Project/product-failure-kaggle-competition-s24/test.csv")
train = read_csv("/Users/gregwolcott/Documents/UNCW/BAN 502 - Predictive Analytics/Course Project/product-failure-kaggle-competition-s24/train.csv")

```

```{r}

summary(train)

```


```{r}
#Convert data to factors
train = train %>% select(-id,-product_code,-attribute_1,-attribute_2,-attribute_3)
train = train %>% mutate(failure = as_factor(failure))
train = train %>% mutate(attribute_0 = as_factor(attribute_0))


```

```{r}
summary(train)
```

```{r}
set.seed(12345) #sets seed for random number generator
imp_final = mice(train, m=5, method='pmm', printFlag=FALSE)
train = complete(imp_final) 


```

```{r}
train_split = initial_split(train, prop = 0.70, strata = failure)
trainingset = training(train_split)
testingset = testing(train_split)
```


```{r}
set.seed(5144)
rf_folds = vfold_cv(trainingset, v=5)
```


```{r}
train_recipe = recipe(failure ~loading + measurement_17+measurement_16+measurement_13+measurement_8, trainingset) %>%
  step_dummy(all_nominal(), -all_outcomes())

rf_model = rand_forest(mtry = tune(), min_n = tune(), trees = 16) %>% 
  set_engine("ranger", importance = "permutation") %>% 
  set_mode("classification")

train_wflow = 
  workflow() %>% 
  add_model(rf_model) %>% 
  add_recipe(train_recipe)

rf_grid = grid_regular(
  mtry(range = c(2, 8)), 
  min_n(range = c(5, 20)), 
  levels = 10
)


```


```{r message=FALSE, warning=FALSE, paged.print=FALSE}
set.seed(123)
rf_res_tuned = tune_grid(
  train_wflow,
  resamples = rf_folds,
  grid = rf_grid #use the tuning grid
)

rf_res_tuned %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  select(mean, min_n, mtry) %>%
  pivot_longer(min_n:mtry,
               values_to = "value",
               names_to = "parameter"
  ) %>%
  ggplot(aes(value, mean, color = parameter)) +
  geom_point(show.legend = FALSE) +
  facet_wrap(~parameter, scales = "free_x") +
  labs(x = NULL, y = "Accuracy")
```


```{r}
best_rf = select_best(rf_res_tuned, "accuracy")

final_rf = finalize_workflow(
  train_wflow,
  best_rf
)

final_rf

final_rf_fit = fit(final_rf, trainingset)
final_rf_fit %>% pull_workflow_fit() %>% vip(geom = "point")
```



```{r}
trainpredrf = predict(final_rf_fit, trainingset)
confusionMatrix(trainpredrf$.pred_class, trainingset$failure, 
                positive = "No")
```



```{r}
train2 = train
train2$preds = trainpredrf$.pred_class
train2
```



```{r}
set.seed(12345) #sets seed for random number generator
test_imp_final = mice(test, m=5, method='pmm', printFlag=FALSE)
test = complete(test_imp_final) 
```


```{r}
skim(test)
```


```{r}
testpredrf = predict(final_rf_fit, test)
test3 = test
test3$preds = testpredrf$.pred_class
```


```{r}
test3
```


```{r}
write_csv(test3,"predictiontest.csv")
```





