```{r}
library(tidyverse)
library(tidymodels)
library(caret)
library(gridExtra)
library(ranger)
library(vip)
library(skimr)
library(ggplot2)
```



```{r}
drug = read_csv("/Users/gregwolcott/Documents/UNCW/BAN 502 - Predictive Analytics/Module 4/drug_data.csv")
```


```{r}
names(drug) = c("ID", "Age", "Gender", "Education", "Country", "Ethnicity",
                "Nscore", "Escore", "Oscore", "Ascore", "Cscore", "Impulsive",
                "SS", "Alcohol", "Amphet", "Amyl", "Benzos", "Caff", "Cannabis",
                "Choc", "Coke", "Crack", "Ecstasy", "Heroin", "Ketamine", "Legalh",
                "LSD", "Meth", "Mushrooms", "Nicotine", "Semer", "VSA")
drug[drug == "CL0"] = "No"
drug[drug == "CL1"] = "No"
drug[drug == "CL2"] = "Yes"
drug[drug == "CL3"] = "Yes"
drug[drug == "CL4"] = "Yes"
drug[drug == "CL5"] = "Yes"
drug[drug == "CL6"] = "Yes"
```



```{r}
drug_clean = drug %>% mutate_at(vars(Age:Ethnicity), funs(as_factor)) %>%
  mutate(Age = factor(Age, labels = c("18_24", "25_34", "35_44", "45_54",
                                      "55_64", "65_"))) %>%
  mutate(Gender = factor(Gender, labels = c("Male", "Female"))) %>%
  mutate(Education = factor(Education, labels = c("Under16", "At16", "At17", "At18",
                                                  "SomeCollege","ProfessionalCert",
                                                  "Bachelors", "Masters",
                                                  "Doctorate"))) %>%
  mutate(Country = factor(Country, labels = c("USA", "NewZealand", "Other", "Australia",
                                                  "Ireland","Canada","UK"))) %>%
      mutate(Ethnicity = factor(Ethnicity, labels = c("Black", "Asian", "White",
                                                      "White/Black", "Other",
                                                      "White/Asian", "Black/Asian"))) %>%
      mutate_at(vars(Alcohol:VSA), funs(as_factor)) %>%
select(-ID)
```

```{r}
drug_clean = drug_clean %>% select(!(Alcohol:Mushrooms)) %>% select(!(Semer:VSA))

str(drug_clean)
```


#1
```{r}
skim(drug_clean)
```



#2
```{r}
set.seed(1234)
drug_split = initial_split(drug_clean, prop = 0.70, strata = Nicotine)
train = training(drug_split)
test = testing(drug_split)

nrow(train)
```

```{r}
summary(train)
```

```{r}
summary(test)
```


#3
```{r}
p1 = ggplot(train, aes(x = Age, fill = Nicotine)) + geom_bar(position = "fill")
p1
```


#4
p2 = ggplot(train, aes(x = Impulsive, fill = Nicotine)) + geom_bar(position = "fill")
p2

#5
```{r}
set.seed(123)
rf_folds = vfold_cv(train, v = 5)

drug_recipe = recipe(Nicotine ~., train) %>%
  step_dummy(all_nominal(), -all_outcomes())

rf_model = rand_forest(mtry = tune(), min_n = tune(), trees = 100) %>% 
  set_engine("ranger", importance = "permutation") %>% 
  set_mode("classification")

drug_wflow = 
  workflow() %>% 
  add_model(rf_model) %>% 
  add_recipe(drug_recipe)

rf_grid = grid_regular(
  mtry(range = c(2, 8)), 
  min_n(range = c(5, 20)), 
  levels = 10
)


set.seed(123)
rf_res_tuned = tune_grid(
  drug_wflow,
  resamples = rf_folds,
  grid = rf_grid #use the tuning grid
)

```


```{r}
rf_res_tuned %>%
  collect_metrics() %>%
  filter(.metric == "accuracy") %>%
  select(mean, min_n, mtry) %>%
  pivot_longer(min_n:mtry,
               values_to = "value",
               names_to = "parameter"
  ) %>%
  ggplot(aes(value, mean, color = parameter)) +
  geom_point(show.legend = FALSE) +
  facet_wrap(~parameter, scales = "free_x") +
  labs(x = NULL, y = "Accuracy")
```



#6
```{r}
best_rf = select_best(rf_res_tuned, "accuracy")

final_rf = finalize_workflow(
  drug_wflow,
  best_rf
)

final_rf
```


final_rf_fit = fit(final_rf, train)
final_rf_fit %>% pull_workflow_fit() %>% vip(geom = "point")


#7
trainpredrf = predict(final_rf_fit, train)
confusionMatrix(trainpredrf$.pred_class, train$Nicotine, 
                positive = "Yes")

#9
testpredrf = predict(final_rf_fit, test)
confusionMatrix(testpredrf$.pred_class, test$Nicotine, 
                positive = "Yes")
